name: build_python312_armel
on:
  push:
    branches:
      - '**'

jobs:
  build_armel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: install option soft
        run: sudo apt update && sudo apt install -y gcc-arm-linux-gnueabi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build binary
        run: ./build-linux.py --target armv7-unknown-linux-gnueabi  --python cpython-3.13 --options freethreaded+noopt+static

      - name: List Dir
        run: ls -lRt ${{ github.workspace }}

      - name: Upload binary to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cpython-3.12-armv7-unknown-linux-gnueabi
          path: ${{ github.workspace }}/dist/*

